/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalloutWrapper: typeof import('./src/components/stateless/callout/callout-wrapper.vue')['default']
    DefaultButton: typeof import('./src/components/stateless/button/default-button.vue')['default']
    FormWrapper: typeof import('./src/components/statefull/form/form-wrapper.vue')['default']
    InputField: typeof import('./src/components/stateless/input/input-field.vue')['default']
    ListItem: typeof import('./src/components/stateless/list/list-item.vue')['default']
    ListWrapper: typeof import('./src/components/stateless/list/list-wrapper.vue')['default']
    LoadingProgress: typeof import('./src/components/stateless/progress/loading-progress.vue')['default']
    PageTitle: typeof import('./src/components/statefull/page-title/page-title.vue')['default']
    ResultWrapper: typeof import('./src/components/statefull/result/result-wrapper.vue')['default']
  }
}
